### ISSUE TITLE
Need some preferences: Font size and spacing

### ISSUE THREAD

**Issue by brnl** [Yubico/yubiclip-android#10]
Hi Guys,

I love the Yubico Authenticator app and use it since today for all my Google Authenticator entries (except for Google self and Lastpass ;-)), but I would like to have two nice preferences:

- I would like to have a bigger font, so it is easier to keep track of what entry I was typing from the list (8 entries).

- I would like to have the numbers grouped by 3 or 2 characters. That way I can read them better as groups, easier to remember in one read.

I am a bit dyslectic, you know, so these features would help me a great lot!

Thanks in advance!

**Comment by minisu** [comment]
You're in the wrong project, this is the [YubiClip](https://play.google.com/store/apps/details?id=com.yubico.yubiclip&hl=en) project. Please open an issue in [yubioath-android](https://github.com/Yubico/yubioath-android) instead.
