### ISSUE TITLE
Android 7 Doesn't Work?

### ISSUE THREAD

**Issue by cFINNY** [Yubico/yubiclip-android#14]
Hey,
Have had yubikeys for many years, including a neo for certain things. The ndef payload was always kept default, I tried yubiclip and it just never worked nomatter what I tried. I assumed it was because my neo was a few years old so got by using the old yubikeys neo demo app that used to be around. However now I just got a brand new NEO and moving everything over, but Yubiclip still does absolutely nothing? Have you guys given up on this or another alternative or??? Using Moto Z Force Droid Android 7, I swipe the NEO and chrome opens at the my.yubi.../neo/... URL, have never gotten any notification toast or otherwise from Yubiclip and it does not put anything on the clipboard. It just doesn't appear to be recognized as able to intercept those URLs??? Again the yubikeyneo demo from a way back works no problem if I have it open, but even that doesn't get an open with prompt at least hasn't in a year or so on my old neo (assuming this is all Android 6 or 7 related?). Any ideas??

**Comment by cFINNY** [comment]
Able to finally get working after reinstalling and clearing chrome defaults a few times, tried in past and didn't work but did this time!:) Should add that note to description on app for those who have issues with it not working as it DOES show its set as default for my.yubico.... Under app permissions even though apparently chrome overrides that? Now I just hope whenever chrome is set as the default next time I hit a link it doesn't circle back around to the same issue

**Comment by binarious** [comment]
Could you please describe the steps you did to fix the problem?
